### ISSUE TITLE
Ask for help about the higher level abstraction

### ISSUE THREAD

**Issue by dragon-zhang** [Amanieu/corosensei#15]
The deeper I understand, the more I can feel the subtlety of this library design.

Recently, I have been trying to build higher level abstractions based on `corosensei`, such as `scheduler` and `event_loop`.

Unfortunately, I encountered some problems during this period and recorded it to [open-coroutine-core-v2](https://github.com/dragon-zhang/open-coroutine-core-v2).

## Problem1
Can't use backtrace, you can see these in :

[src/coroutine/mod.rs:287](https://github.com/dragon-zhang/open-coroutine-core-v2/blob/master/src/coroutine/mod.rs)

[src/scheduler.rs:182](https://github.com/dragon-zhang/open-coroutine-core-v2/blob/master/src/scheduler.rs)

## Problem2
Can't pass the complex preemptive schedule CI, see it in :

[src/scheduler.rs:228](https://github.com/dragon-zhang/open-coroutine-core-v2/blob/master/src/scheduler.rs)

Note: [monitor mod](https://github.com/dragon-zhang/open-coroutine-core-v2/blob/master/src/monitor.rs) register the `signal handler`.

Could you please to help me solve them ?

**Comment by Amanieu** [comment]
Your stack size is too small. Try increasing it.

**Comment by dragon-zhang** [comment]
> Your stack size is too small. Try increasing it.

It works ! Thanks for helping me to solve `Problem1`.

**Comment by Amanieu** [comment]
First of all you need bigger stacks. 4*page_size is not enough for backtraces and signal handlers. I suggest at least 64KB, but you can use 1MB when testing just to be sure.

Secondly, manual preemption using signal handlers is very unsafe. If you do this, you are not allowed to call any function in the coroutine that allocate memory or acquire locks (since they could cause deadlocks when suspended), which prevents you from using most functions from `std` and `libc`. I strongly suggest using cooperative preemption by checking for a flag at specific points instead.

**Comment by dragon-zhang** [comment]
`suggest at least 64KB, but you can use 1MB when testing just to be sure` got it ! The previous 4*page_size were tested locally and passed, so they were submitted directly. However, there are still some problems, I'll try it until CI passed.

`which prevents you from using most functions from std and libc` can be handled by `hook` technology, the original `nanosleep` will be interrupted by the signal, but the `hooked nanosleep` can be uninterruptable.

`using cooperative preemption by checking for a flag at specific points instead` you mean let the user to `suspend` ? Like :
```rust
    #[test]
    fn with_suspend() {
        let scheduler = Scheduler::new();
        let _ = scheduler.submit(|suspender, _| {
            println!("[coroutine1] suspend");
//proactively suspend
            suspender.suspend();
            println!("[coroutine1] back");
            result(1)
        });
        scheduler.try_schedule();
    }
```

**Comment by dragon-zhang** [comment]
Good news, referring to the implementation of `goroutine`, I changed the PC register:
```rust
use libc::{sigaction, siginfo_t, ucontext_t, SA_NODEFER, SA_RESTART, SA_SIGINFO, SIGINT};
use std::os::unix::thread::JoinHandleExt;

static mut RUN: bool = true;

unsafe extern "C" fn yields() {
    println!("yielded after signal_handler returned");
    RUN = false;
}

unsafe extern "C" fn signal_handler(signum: i32, _siginfo: &siginfo_t, context: &mut ucontext_t) {
    cfg_if::cfg_if! {
        if #[cfg(all(
            any(target_os = "linux", target_os = "android"),
            target_arch = "x86_64",
        ))] {
            context.uc_mcontext.gregs[libc::REG_RIP as usize] = yields as i64;
        } else if #[cfg(all(
                    any(target_os = "linux", target_os = "android"),
                    target_arch = "x86",
        ))] {
            context.uc_mcontext.gregs[libc::REG_EIP as usize] = yields as i32;
        } else if #[cfg(all(
                    any(target_os = "linux", target_os = "android"),
                    target_arch = "aarch64",
        ))] {
            context.uc_mcontext.pc = yields as libc::c_ulong;
        } else if #[cfg(all(
                    any(target_os = "linux", target_os = "android"),
                    target_arch = "arm",
        ))] {
            context.uc_mcontext.arm_pc = yields as libc::c_ulong;
        } else if #[cfg(all(
                    any(target_os = "linux", target_os = "android"),
                    any(target_arch = "riscv64", target_arch = "riscv32"),
        ))] {
            context.uc_mcontext.__gregs[libc::REG_PC] = yields as libc::c_ulong;
        } else if #[cfg(all(target_vendor = "apple", target_arch = "aarch64"))] {
            (*context.uc_mcontext).__ss.__pc = yields as u64;
        } else if #[cfg(all(target_vendor = "apple", target_arch = "x86_64"))] {
            (*context.uc_mcontext).__ss.__rip = yields as u64;
        } else {
            compile_error!("Unsupported platform");
        }
    }
    println!("Received signal {}", signum);
}

fn main() {
    let handler = std::thread::spawn(|| unsafe {
        let mut sa: sigaction = std::mem::zeroed();
        sa.sa_sigaction = signal_handler as usize;
        libc::sigemptyset(&mut sa.sa_mask);
        sa.sa_flags = SA_SIGINFO | SA_RESTART | SA_NODEFER;
        if sigaction(SIGINT, &sa, std::ptr::null_mut()) == -1 {
            println!("Failed to register handler for SIGINT");
            return;
        }

        while RUN {
            println!("Waiting for signal...");
            libc::sleep(1);
        }
    });
    let pthread = handler.as_pthread_t();
    unsafe {
        libc::sleep(1);
        libc::pthread_kill(pthread, SIGINT);
        libc::sleep(1);
        handler.join().unwrap();
    }
}
```
The simplified code above runs well on macos(both `arm64` and `x86_64` mac) and outputs:
```text
Waiting for signal...
Received signal 2
yielded after signal_handler returned
```

Excitingly, I saw the results I had been wanting to see for a long time in [preemptive.rs](https://github.com/dragon-zhang/open-coroutine-core-v2/blob/master/examples/preemptive.rs):
```text
coroutine1 launched
loop1
coroutine2 launched
loop2
loop2
coroutine3 launched
loop1
loop1
loop2 end
loop1 end
```
Which means that the complex preemptive scheduling has been successfully implemented !
:)

But the bad news is that [it](https://github.com/dragon-zhang/open-coroutine-core-v2/blob/master/examples/change_pc.rs) failed to run on Linux :(
```text
Waiting for signal...
Received signal 2
/home/runner/work/_temp/2003bf10-5f5a-4f75-a162-6a6dbc3ee081.sh: line 1:  3033 Segmentation fault      (core dumped) sudo bash -c "sudo -u runner RUSTUP_TOOLCHAIN=stable RUST_BACKTRACE=1 /home/runner/.cargo/bin/cargo run --example change_pc --release"
Error: Process completed with exit code 139.
```
The problem should be where the PC register was changed, but I don't know how to fix it correctly.
I'm sorry to seek your help again.

**Comment by dragon-zhang** [comment]
Problem2 is solved by https://github.com/dragon-zhang/open-coroutine-core-v2/commit/0281a61408715069eb0c20f0ab9c59a8c51dcc85
