### ISSUE TITLE
Maybe unsound in ValgrindStackRegistration::new

### ISSUE THREAD

**Issue by lwz23** [Amanieu/corosensei#45]
Hello, thank you for your contribution in this project, I am scanning the unsoundness problem in rust project.
I notice the following code:
```
pub struct ValgrindStackRegistration {
    id: Value,
}

impl ValgrindStackRegistration {
    /// Registers the given region of memory as a stack so that Valgrind can
    /// properly recognize legitimate stack switches.
    #[inline]
    pub fn new(addr: *mut u8, len: usize) -> Self {
        Self {
            id: unsafe {
                valgrind_request(
                    0,
                    &[
                        STACK_REGISTER,
                        addr as Value,
                        addr as Value + len as Value,
                        0,
                        0,
                        0,
                    ],
                )
            },
        }
    }
}

impl Drop for ValgrindStackRegistration {
    #[inline]
    fn drop(&mut self) {
        unsafe {
            valgrind_request(0, &[STACK_DEREGISTER, self.id, 0, 0, 0, 0]);
        }
    }
}
```
Considering that `pub mod stack`, and `new`  is also a pub function. I assume that users can directly call this function. This potential situation could result in `addr` being a null pointer, and directly use it to crate a `Value` type might trigger undefined behavior (UB). For safety reasons, I felt it necessary to report this issue. If you have performed checks elsewhere that ensure this is safe, please don’t take offense at my raising this issue.
I suggest Several possible fixes: 
1. If there is no external usage for `ValgrindStackRegistration` or `new`, they should not marked as `pub`, at least its `new` should not marked as `pub` 
2. `new` method should add additional check for null pointer.
3. mark new method as unsafe and proper doc to let users know that they should provide valid Pointers.

**Comment by Amanieu** [comment]
First of all this is an internal type that is not exported outside the crate.

Secondly, it's not unsound to pass in invalid pointers since these are just treated as hints by Valgrind. The hints don't affect program execution, only the diagnostics reported by Valgrind.

**Comment by lwz23** [comment]
You're right! After verification I found that passing a null pointer here does not cause UB. But for the first point I want to clarify, it seems that this can be used externally by crate. As follows:
```
extern crate corosensei;

use std::ptr;

use corosensei::stack::valgrind::ValgrindStackRegistration;
fn main() {
    let a:*mut u8=ptr::null_mut();
    let b=ValgrindStackRegistration::new(a, 0);
    println!("{:?}",b);
}
```
If this is an internal type and does not want to be used externally, perhaps `ValgrindStackRegistration` should not be declared as pub?

**Comment by Amanieu** [comment]
Oh you're right it actually is public. I remembered incorrectly.

In that case it's fine to just leave it as it is.

**Comment by lwz23** [comment]
I agree, it doesn't seem to cause UB.
