### ISSUE TITLE
Embedded use with ARM M0+

### ISSUE THREAD

**Issue by kpishere** [Amanieu/corosensei#6]
@Amanieu I've learned lots trying to use your crate ;)  But still, I'm not seeing how/where this error is coming from.

The state of my project is in repo+branch [https://github.com/kpishere/rp2040-project-template/tree/steps](url).

If I include the following lines 

```
let mut coroutine = Coroutine::with_stack(stack, |yielder, input| {
        info!("[coroutine] coroutine started with input {}", input);
        for i in 0..5 {
            info!("[coroutine] yielding {}", i);
            let input: i32 = yielder.suspend(i);
            info!("[coroutine] got {} from parent", input)
        }
        info!("[coroutine] exiting coroutine");
    });
```

I get this error 

```
  = note: rust-lld: error: section '.ARM.extab' will not fit in region 'BOOT2': overflowed by 16 bytes
          rust-lld: error: section '.ARM.extab' will not fit in region 'BOOT2': overflowed by 16 bytes
          rust-lld: error: section '.ARM.extab' will not fit in region 'BOOT2': overflowed by 16 bytes
          rust-lld: error: section .vector_table virtual address range overlaps with .ARM.extab
          >>> .vector_table range is [0x10000100, 0x100001A7]
          >>> .ARM.extab range is [0x10000100, 0x1000010F]
          
          rust-lld: error: section .vector_table load address range overlaps with .ARM.extab
          >>> .vector_table range is [0x10000100, 0x100001A7]
          >>> .ARM.extab range is [0x10000100, 0x1000010F]
```

I don't see any .ARM.extab section in your crate.  Not sure where to look.

**Comment by kpishere** [comment]
@Amanieu Yep, it links now.  Thanks.  Not understanding why that appears though.

It crashes with a HardFault but will investigate that more.  FYI .. attached picture of hard fault
![Screen Shot 2022-07-06 at 11 41 05 AM](https://user-images.githubusercontent.com/25204173/177590335-d42d144c-743a-4031-97ac-f770d2db33f5.png)

.

**Comment by Amanieu** [comment]
That's stopped at a breakpoint. I need the disassembly at the point of the crash.

**Comment by kpishere** [comment]
Yeah, trying to find that.  It get stuck in hard fault loop, would R7 have the return address of where it came from at that point? (sorry if dumb question) That point  0x2003F794 .. I'm looking there

**Comment by kpishere** [comment]
Ok, had to switch to a view I'm more familiar with .. 

![Screen Shot 2022-07-06 at 3 03 36 PM](https://user-images.githubusercontent.com/25204173/177625733-58dc0218-fb58-42d9-b529-86d1a939a6db.png)

And another view showing other registers .. 
![Screen Shot 2022-07-06 at 3 03 57 PM](https://user-images.githubusercontent.com/25204173/177625828-81c8035c-800e-408c-8131-a53225641808.png)

The first step from what is shown throws an exception.  It is a disconnect in the opcode not being thumb or the PC register not having the last bit set correctly?

**Comment by Amanieu** [comment]
If you single-step one instruction at a time (`si` in gdb), can you pin-point the exact instruction that causes the fault?

**Comment by kpishere** [comment]
Oh! `si`, forgot about that.  Thanks ok.  this makes more sense ... 

![Screen Shot 2022-07-06 at 3 35 29 PM](https://user-images.githubusercontent.com/25204173/177629192-a0cdbbca-0d28-42de-bd9c-a4fcd2e1df0c.png)

![Screen Shot 2022-07-06 at 3 34 59 PM](https://user-images.githubusercontent.com/25204173/177629219-83fd27fa-8bae-4c9d-959e-6e4734a4a00a.png)

**Comment by Amanieu** [comment]
Well I can't figure it out. Do you think it would be possible to run this in QEMU so I could try it out myself?

**Comment by kpishere** [comment]
Well, I've used QEMU before for emulating Pi Zero.  Let me see if I can re-produce the same issue in QEMU ... got to set it up for PICO and Rust environment etc.  You're making me learn all the tools! :) Thanks!

**Comment by kpishere** [comment]
@Amanieu Sadly, not seeing steps to do, think it is a low priority for qemu, thought I'd seen it for thumb7. Anyhow, stack is clearly corrupted and thought I'd look at it.  Looking at first steps where stack is used.  I suspect the stack is created in low memory and isn't writable.  This may be my allocator that is the problem? 

The stack address should not be 0x1000.    That appears to be ROM.  It should start with 0x20000000 as this is the beginning of SRAM.
 
![Screen Shot 2022-07-06 at 9 35 27 PM](https://user-images.githubusercontent.com/25204173/177671628-9d097ca9-a4fc-44ef-bc41-d2878e7a26ae.png)

ROM 0x00000000
XIP 0x10000000
SRAM 0x20000000
APB Peripherals 0x40000000

**Comment by kpishere** [comment]
@Amanieu Happiness is!  My heap only had 1K available at initialization and the stack is minimum 4K.  Increased heap to 16K available and all is good.!

Thank you for your support and this crate!

```
~/defmt.sh 
INFO  Program start
└─ rp2040_project_template::__cortex_m_rt_main @ src/main.rs:51
INFO  [main] resuming coroutine with argument 100
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:98
INFO  [coroutine] coroutine started with input 100
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:87
INFO  [coroutine] yielding 0
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:89
INFO  [main] got 0 from coroutine
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:100
INFO  on!
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:105
INFO  off!
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:108
INFO  [main] resuming coroutine with argument 101
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:98
INFO  [coroutine] got 101 from parent
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:91
INFO  [coroutine] yielding 1
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:89
INFO  [main] got 1 from coroutine
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:100
INFO  on!
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:105
INFO  off!
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:108
INFO  [main] resuming coroutine with argument 102
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:98
INFO  [coroutine] got 102 from parent
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:91
INFO  [coroutine] yielding 2
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:89
INFO  [main] got 2 from coroutine
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:100
INFO  on!
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:105
INFO  off!
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:108
INFO  [main] resuming coroutine with argument 103
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:98
INFO  [coroutine] got 103 from parent
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:91
INFO  [coroutine] yielding 3
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:89
INFO  [main] got 3 from coroutine
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:100
INFO  on!
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:105
INFO  off!
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:108
INFO  [main] resuming coroutine with argument 104
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:98
INFO  [coroutine] got 104 from parent
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:91
INFO  [coroutine] yielding 4
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:89
INFO  [main] got 4 from coroutine
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:100
INFO  on!
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:105
INFO  off!
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:108
INFO  [main] resuming coroutine with argument 105
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:98
INFO  [coroutine] got 105 from parent
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:91
INFO  [coroutine] exiting coroutine
└─ rp2040_project_template::__cortex_m_rt_main::{closure#0} @ src/main.rs:93
```

**Comment by Amanieu** [comment]
You can probably get away with a smaller stack. Also since you don't have a guard page, you need to make sure you don't overflow the stack.
