### ISSUE TITLE
Support for SPARC64

### ISSUE THREAD

**Issue by Richard-Rogalski** [Amanieu/corosensei#8]
Hello!!

Sorry, I have not had the opportunity to look through your codebase to see how trivial adding a CPU target is. However, it looks like it is all rust, which is a good start :D 

So, I'm wondering:

Would you be open to this project having support for sparc64? and:  
How difficult is it to add new targets?

I do not have any experience in rust, but I could do my best to take a crack at it :). Also, I would be more than willing to lend you SSH access to my sparc, if you wanted to take a crack at it yourself.

I appreciate your time :)

**Comment by Amanieu** [comment]
Unfortunately adding a new target is quite complicated, see the [AArch64 port](https://github.com/Amanieu/corosensei/blob/master/src/arch/aarch64.rs) for an example.

Also this crate heavily relies on Rust inline assembly, which is currently [not supported](https://doc.rust-lang.org/nightly/unstable-book/language-features/asm-experimental-arch.html) on SPARC. The first step would be to add inline assembly support for SPARC to rustc ([instructions](https://rustc-dev-guide.rust-lang.org/asm.html#adding-support-for-new-architectures)).

**Comment by Richard-Rogalski** [comment]
Thanks for the reply!!

Well, bummed out that adding a new target is complicated :\. But, adding inline assembly support seems (relatively!) easy, I'll take a crack there :)

**Comment by Richard-Rogalski** [comment]
Closing this, seems nobody else wants this, and I have since moved on :)
