### ISSUE TITLE
scheduler abstraction discuss

### ISSUE THREAD

**Issue by dragon-zhang** [Amanieu/corosensei#9]
I see that this crate has not yet abstracted the `scheduler`. Is there is a plan to add it?

If the answer is yes, can we support `work-stealing` and `preemption scheduling`?

As for `work-stealing`, I'm not sure which crate should be used in this crate.

As for `preemption scheduling`, here is an instance that can run successfully on my `MacBook Pro`:
```rust
use std::os::unix::thread::JoinHandleExt;
use std::thread;
use std::time::Duration;

static mut RUN: bool = true;

unsafe fn preempt() {
    println!("preemption scheduling happens");
    RUN = false;
}

fn main() -> thread::Result<()> {
    let pthread = thread::spawn(|| unsafe {
        println!("register signal");
        libc::signal(libc::SIGURG, preempt as usize);
        println!("start loop");
        while RUN {}
        println!("finished");
    }).as_pthread_t();
    thread::sleep(Duration::from_millis(1000));
    thread::spawn(move || unsafe {
        libc::pthread_kill(pthread, libc::SIGURG);
        println!("pthread signaled");
        thread::sleep(Duration::from_millis(1000));
    }).join()
}
```
As far as I know, `goroutine` also uses a similar mechanism.

Looking forward to your reply :)

**Comment by Amanieu** [comment]
This crate only provides basic support for safely switching between stacks. Additional functionality such as schedulers is outside the scope of this crate, and should be implemented in a separate crate.

**Comment by dragon-zhang** [comment]
copy that, best wishes !
